
module.exports = {
  BOOKING_STATUSES: ["PENDING", "CLOSED", "OPEN"],
  PACKAGE_TYPES: ["HOUR", "DAY", "WEEK", "MONTH"],
  CURRENCY_UNIT: 'VND',
  DEFAULT_PACKAGE_TYPE: 'HOUR',
  CHANGE_HOUR_TO_DAY_PACKAGE: 7,
}
